name: Build For platforms
on: [push]

jobs:
  build:
    strategy:

      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: cd .. && cd .. && dir && start \Snake\bin\windows\Snake.exe
